-keep class dev.firecrawl.anydoc.** { *; }
-keep class com.sun.jna.** { *; }
-keepclassmembers class * extends com.sun.jna.** { public *; }
-dontwarn java.awt.*
-dontwarn javax.swing.*
-dontwarn com.sun.jna.platform.**
